<?php

namespace App\Filament\Resources;

use App\Filament\Resources\UserResource\Pages;
use App\Filament\Resources\UserResource\Widgets\UserOverview;
use App\Filament\Resources\UserResource\Widgets\UserStatsWidget;
use App\Models\User;
use Carbon\Carbon;
use Filament\Forms;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use AymanAlhattami\FilamentPageWithSidebar\FilamentPageSidebar;
use AymanAlhattami\FilamentPageWithSidebar\PageNavigationItem;

class UserResource extends Resource
{
    protected static ?string $model = User::class;

    protected static ?string $navigationIcon = 'heroicon-o-users';

    protected static ?int $navigationSort = 1;

    protected static ?string $recordTitleAttribute = 'name';

    public static function getNavigationGroup(): ?string
    {
        return __('user.user_management');
    }

    public static function getNavigationLabel(): string
    {
        return __('user.users');
    }

    public static function getModelLabel(): string
    {
        return __('user.user');
    }

    public static function getPluralModelLabel(): string
    {
        return __('user.users');
    }

    /**
     * @dev @victormsalatiel
     * @return bool
     */
    public static function canAccess(): bool
    {
        return auth()->user()->hasRole('admin');
    }

    /**
     * @param Model $record
     * @return string
     */
    public static function getGlobalSearchResultTitle(Model $record): string
    {
        return $record->name; // TODO: Change the autogenerated stub
    }

    /**
     * @return string[]
     */
    public static function getGloballySearchableAttributes(): array
    {
        return ['name', 'email']; // TODO: Change the autogenerated stub
    }

    /**
     * @param Model $record
     * @return FilamentPageSidebar
     */
    public static function sidebar(Model $record): FilamentPageSidebar
    {
        return FilamentPageSidebar::make()
            ->setTitle($record->name)
            ->setDescription($record->created_at)
            ->setNavigationItems([
                PageNavigationItem::make(__('base.list_user'))
                    ->translateLabel()
                    ->url(static::getUrl('index'))->icon('heroicon-o-user-group')
                    ->isActiveWhen(function () {
                        return request()->routeIs(static::getRouteBaseName() . '.list-users');
                    }),
                PageNavigationItem::make(__('base.view_user'))
                    ->translateLabel()
                    ->url(static::getUrl('view', ['record' => $record->id]))->icon('heroicon-o-user')
                    ->isActiveWhen(function () {
                        return request()->routeIs(static::getRouteBaseName() . '.view');
                    }),
                PageNavigationItem::make(__('base.edit_user'))
                    ->translateLabel()
                    ->url(static::getUrl('edit', ['record' => $record->id]))
                    ->icon('heroicon-o-pencil-square')
                    ->isActiveWhen(function () {
                        return request()->routeIs(static::getRouteBaseName() . '.edit');
                    }),
                PageNavigationItem::make(__('base.change_password'))
                    ->translateLabel()
                    ->url(static::getUrl('password.change', ['record' => $record->id]))
                    ->icon('heroicon-o-key')
                    ->isActiveWhen(function () {
                        return request()->routeIs(static::getRouteBaseName() . '.password.change');
                    }),

            ]);
    }


    /**
     * @param Form $form
     * @return Form
     */
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make(__('user.personal_information'))
                    ->schema([
                        Forms\Components\TextInput::make('name')
                            ->label(__('user.name'))
                            ->placeholder(__('user.enter_name'))
                            ->required()
                            ->maxLength(191),
                        Forms\Components\TextInput::make('email')
                            ->label(__('user.email'))
                            ->placeholder(__('user.enter_email'))
                            ->email()
                            ->required()
                            ->unique(ignoreRecord: true)
                            ->maxLength(191),
                        Forms\Components\TextInput::make('cpf')
                            ->label(__('user.cpf'))
                            ->placeholder(__('user.enter_cpf'))
                            ->mask('999.999.999-99')
                            ->maxLength(191),
                        Forms\Components\TextInput::make('phone')
                            ->label(__('user.phone'))
                            ->placeholder(__('user.enter_phone'))
                            ->tel()
                            ->mask('(99) 99999-9999')
                            ->maxLength(191),
                        Forms\Components\Select::make('roles')
                            ->label(__('user.roles'))
                            ->relationship('roles', 'name')
                            ->multiple()
                            ->preload()
                            ->required()
                            ->helperText(__('user.select_roles')),
                        Forms\Components\TextInput::make('password')
                            ->label(__('user.password'))
                            ->password()
                            ->required(fn ($context) => $context === 'create')
                            ->dehydrated(fn ($state) => filled($state))
                            ->minLength(8)
                            ->maxLength(191)
                            ->helperText(__('user.leave_blank_password')),
                    ])->columns(3),

                Forms\Components\Section::make(__('user.affiliate_settings'))
                    ->schema([
                        Forms\Components\Select::make('inviter')
                            ->label(__('user.affiliate'))
                            ->placeholder(__('user.select_affiliate'))
                            ->relationship(name: 'affiliate', titleAttribute: 'name')
                            ->options(
                                fn($get) => User::query()->pluck('name', 'id')
                            )
                            ->searchable()
                            ->preload(),
                        Forms\Components\TextInput::make('affiliate_revenue_share')
                            ->label(__('user.revenue_share'))
                            ->numeric()
                            ->default(0)
                            ->suffix('%')
                            ->minValue(0)
                            ->maxValue(100),
                        Forms\Components\TextInput::make('affiliate_revenue_share_fake')
                            ->label(__('user.revenue_share_fake'))
                            ->numeric()
                            ->default(0)
                            ->suffix('%')
                            ->minValue(0)
                            ->maxValue(100),
                        Forms\Components\TextInput::make('affiliate_cpa')
                            ->label(__('user.cpa'))
                            ->numeric()
                            ->default(0)
                            ->prefix(\Helper::getSetting()->prefix ?? '$'),
                        Forms\Components\TextInput::make('affiliate_baseline')
                            ->label(__('user.baseline'))
                            ->numeric()
                            ->default(0)
                            ->prefix(\Helper::getSetting()->prefix ?? '$'),
                    ])->columns(5)
                    ->collapsible()
                    ->collapsed(),

                Forms\Components\Section::make(__('user.status_and_permissions'))
                    ->schema([
                        Forms\Components\Select::make('status')
                            ->label(__('user.account_status'))
                            ->options([
                                'active' => __('user.active'),
                                'suspended' => __('user.suspended'),
                                'inactive' => __('user.inactive'),
                            ])
                            ->default('active')
                            ->required()
                            ->helperText(__('user.account_status_help')),
                        Forms\Components\Toggle::make('banned')
                            ->label(__('user.blocked'))
                            ->helperText(__('user.blocked_help'))
                            ->default(false),
                        Forms\Components\Toggle::make('is_demo_agent')
                            ->label(__('user.influencer'))
                            ->helperText(__('user.influencer_help'))
                            ->default(false),
                        Forms\Components\DateTimePicker::make('email_verified_at')
                            ->label(__('user.email_verified_at'))
                            ->helperText(__('user.email_verified_at')),
                    ])->columns(2),
            ]);
    }

    /**
     * @param Table $table
     * @return Table
     */
    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('created_at', 'desc')
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->label(__('user.name'))
                    ->searchable()
                    ->sortable(),
                Tables\Columns\TextColumn::make('email')
                    ->label(__('user.email'))
                    ->searchable()
                    ->sortable(),
                Tables\Columns\TextColumn::make('roles.name')
                    ->label(__('user.role'))
                    ->badge()
                    ->colors([
                        'success' => 'admin',
                        'primary' => 'afiliado',
                        'warning' => 'user',
                    ])
                    ->searchable(),
                Tables\Columns\TextColumn::make('wallet.total_balance')
                    ->label(__('user.balance'))
                    ->money('BRL')
                    ->sortable(),
                Tables\Columns\IconColumn::make('banned')
                    ->label(__('user.blocked'))
                    ->boolean()
                    ->trueIcon('heroicon-o-x-circle')
                    ->falseIcon('heroicon-o-check-circle')
                    ->trueColor('danger')
                    ->falseColor('success'),
                Tables\Columns\TextColumn::make('status')
                    ->label(__('user.status'))
                    ->badge()
                    ->colors([
                        'success' => 'active',
                        'warning' => 'suspended',
                        'danger' => 'inactive',
                    ])
                    ->formatStateUsing(fn (string $state): string => __('user.' . $state))
                    ->sortable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->label(__('user.registration_date'))
                    ->dateTime('d/m/Y H:i')
                    ->sortable(),
                Tables\Columns\TextColumn::make('email_verified_at')
                    ->label(__('user.email_verified'))
                    ->dateTime('d/m/Y H:i')
                    ->toggleable(isToggledHiddenByDefault: true)
                    ->sortable(),
                Tables\Columns\TextColumn::make('updated_at')
                    ->label(__('user.last_update'))
                    ->dateTime('d/m/Y H:i')
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('status')
                    ->label(__('user.status'))
                    ->options([
                        'active' => __('user.active'),
                        'suspended' => __('user.suspended'),
                        'inactive' => __('user.inactive'),
                    ]),
                Tables\Filters\TernaryFilter::make('banned')
                    ->label(__('user.blocked'))
                    ->placeholder(__('user.all'))
                    ->trueLabel(__('user.yes'))
                    ->falseLabel(__('user.no')),
                Tables\Filters\SelectFilter::make('roles')
                    ->label(__('user.role'))
                    ->relationship('roles', 'name')
                    ->multiple()
                    ->preload(),
                Filter::make('created_at')
                    ->form([
                        DatePicker::make('created_from')->label(__('user.created_from')),
                        DatePicker::make('created_until')->label(__('user.created_until')),
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        return $query
                            ->when(
                                $data['created_from'],
                                fn (Builder $query, $date): Builder => $query->whereDate('created_at', '>=', $date),
                            )
                            ->when(
                                $data['created_until'],
                                fn (Builder $query, $date): Builder => $query->whereDate('created_at', '<=', $date),
                            );
                    })
                    ->indicateUsing(function (array $data): array {
                        $indicators = [];

                        if ($data['created_from'] ?? null) {
                            $indicators['created_from'] = 'Criado a partir de ' . Carbon::parse($data['created_from'])->toFormattedDateString();
                        }

                        if ($data['created_until'] ?? null) {
                            $indicators['created_until'] = 'Created until ' . Carbon::parse($data['created_until'])->toFormattedDateString();
                        }

                        return $indicators;
                    })
            ])
            ->actions([
                Tables\Actions\ActionGroup::make([
                    Tables\Actions\ViewAction::make()
                        ->label(__('user.view'))
                        ->icon('heroicon-o-eye'),
                    Tables\Actions\EditAction::make()
                        ->label(__('user.edit'))
                        ->icon('heroicon-o-pencil-square'),
                    Tables\Actions\Action::make('changePassword')
                        ->label(__('user.change_password'))
                        ->icon('heroicon-o-key')
                        ->color('warning')
                        ->url(fn (User $record): string => route('filament.admin.resources.users.password.change', ['record' => $record])),
                    Tables\Actions\Action::make('suspend')
                        ->label(__('user.suspend'))
                        ->icon('heroicon-o-pause-circle')
                        ->color('warning')
                        ->requiresConfirmation()
                        ->visible(fn (User $record): bool => $record->status !== 'suspended')
                        ->action(function (User $record) {
                            $record->update(['status' => 'suspended']);
                        })
                        ->successNotificationTitle(__('user.user_suspended_successfully')),
                    Tables\Actions\Action::make('activate')
                        ->label(__('user.activate'))
                        ->icon('heroicon-o-check-circle')
                        ->color('success')
                        ->requiresConfirmation()
                        ->visible(fn (User $record): bool => $record->status !== 'active')
                        ->action(function (User $record) {
                            $record->update(['status' => 'active']);
                        })
                        ->successNotificationTitle(__('user.user_activated_successfully')),
                    Tables\Actions\Action::make('block')
                        ->label(fn (User $record): string => $record->banned ? __('user.unblock') : __('user.block'))
                        ->icon(fn (User $record): string => $record->banned ? 'heroicon-o-lock-open' : 'heroicon-o-lock-closed')
                        ->color(fn (User $record): string => $record->banned ? 'success' : 'danger')
                        ->requiresConfirmation()
                        ->action(function (User $record) {
                            $record->update(['banned' => !$record->banned]);
                        })
                        ->successNotificationTitle(fn (User $record): string => $record->banned ? __('user.user_blocked_successfully') : __('user.user_unblocked_successfully')),
                    Tables\Actions\Action::make('assignRole')
                        ->label(__('user.assign_role'))
                        ->icon('heroicon-o-user-group')
                        ->color('info')
                        ->form([
                            Forms\Components\Select::make('roles')
                                ->label(__('user.roles'))
                                ->relationship('roles', 'name')
                                ->multiple()
                                ->preload()
                                ->required(),
                        ])
                        ->action(function (User $record, array $data) {
                            $record->syncRoles($data['roles']);
                        })
                        ->successNotificationTitle(__('user.roles_updated_successfully')),
                    Tables\Actions\DeleteAction::make()
                        ->label(__('user.delete'))
                        ->icon('heroicon-o-trash'),
                ])->tooltip(__('user.actions')),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\BulkAction::make('suspend')
                        ->label(__('user.suspend_selected'))
                        ->icon('heroicon-o-pause-circle')
                        ->color('warning')
                        ->requiresConfirmation()
                        ->action(function ($records) {
                            $records->each->update(['status' => 'suspended']);
                        })
                        ->deselectRecordsAfterCompletion()
                        ->successNotificationTitle(__('user.users_suspended_successfully')),
                    Tables\Actions\BulkAction::make('activate')
                        ->label(__('user.activate_selected'))
                        ->icon('heroicon-o-check-circle')
                        ->color('success')
                        ->requiresConfirmation()
                        ->action(function ($records) {
                            $records->each->update(['status' => 'active']);
                        })
                        ->deselectRecordsAfterCompletion()
                        ->successNotificationTitle(__('user.users_activated_successfully')),
                    Tables\Actions\BulkAction::make('block')
                        ->label(__('user.block_selected'))
                        ->icon('heroicon-o-lock-closed')
                        ->color('danger')
                        ->requiresConfirmation()
                        ->action(function ($records) {
                            $records->each->update(['banned' => 1]);
                        })
                        ->deselectRecordsAfterCompletion()
                        ->successNotificationTitle(__('user.users_blocked_successfully')),
                    Tables\Actions\BulkAction::make('unblock')
                        ->label(__('user.unblock_selected'))
                        ->icon('heroicon-o-lock-open')
                        ->color('success')
                        ->requiresConfirmation()
                        ->action(function ($records) {
                            $records->each->update(['banned' => 0]);
                        })
                        ->deselectRecordsAfterCompletion()
                        ->successNotificationTitle(__('user.users_unblocked_successfully')),
                    Tables\Actions\DeleteBulkAction::make()
                        ->label(__('user.delete_selected')),
                ]),
            ])
            ->emptyStateActions([
                Tables\Actions\CreateAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    /**
     * @return string[]
     */
    public static function getWidgets(): array
    {
        return [
            UserStatsWidget::class,
            UserOverview::class,
        ];
    }

    /**
     * @return array|\Filament\Resources\Pages\PageRegistration[]
     */
    public static function getPages(): array
    {
        return [
            'index' => Pages\ListUsers::route('/'),
            'create' => Pages\CreateUser::route('/create'),
            'edit' => Pages\EditUser::route('/{record}/edit'),
            'view' => Pages\ViewUser::route('/{record}/view'),
            'detail' => Pages\DetailUser::route('/{record}/detail'),
            'password.change' => Pages\ChangePasswordUser::route('/{record}/password/change'),
        ];
    }
}
